### ISSUE TITLE
v0.0.7版本有点卡顿的感觉

### ISSUE THREAD

**Issue by Kun9527** [ChatGPT-Desktop/ChatGPT-Desktop#100]
v0.0.7版本有点卡顿的感觉，没有0.0.6流畅

**Comment by Kun9527** [comment]
比较明显的就是0.0.6的文字内容是很丝滑出现，0.0.7一下子就返回大量文字，感觉到明显的卡顿

**Comment by bilibili-ayang** [comment]
方便录个屏吗？然后提供一下电脑信息！

**Comment by Kun9527** [comment]
> 方方便录个画面吗？然后提供一下电脑信息！
Windows11
![image](https://user-images.githubusercontent.com/52945979/227782045-64eba5b8-2353-4e06-8383-8727f484d426.png)

**Comment by bilibili-ayang** [comment]
电脑看着很不错，但是我们这边 windows 测试没啥卡顿的情况，具体还得录视频才知道！

**Comment by Kun9527** [comment]
> 电脑看着很不错，但是我们这边 windows 测试没啥卡顿的情况，具体还得录视频才知道！

有可能是我的网络问题吧

**Comment by bilibili-ayang** [comment]
> > 电脑看着很不错，但是我们这边 windows 测试没啥卡顿的情况，具体还得录视频才知道！
> 
> 有可能是我的网络问题吧

跟网络也会有关系。新版本加入了隐藏 token 实时渲染的开关，可以关闭试试，如果还是卡顿，那跟网络有很大关系！

**Comment by Kun9527** [comment]
好的，我试下&nbsp;


?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月27日(星期一) 上午9:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ChatGPT-Desktop/ChatGPT-Desktop] v0.0.7版本有点卡顿的感觉 (Issue #100)





   
电脑看着很不错，但是我们这边 windows 测试没啥卡顿的情况，具体还得录视频才知道！
  
有可能是我的网络问题吧
  
跟网络也会有关系。新版本加入了隐藏 token 实时渲染的开关，可以关闭试试，如果还是卡顿，那跟网络有很大关系！
