### ISSUE TITLE
ubuntu下 快捷键没用

### ISSUE THREAD

**Issue by renwofei423** [ChatGPT-Desktop/ChatGPT-Desktop#108]
最新的0.08版本，界面本身没什么问题，

就是快捷键无法隐藏、显示出窗口来。

换了一些按键组合，也没用

ubuntu22.04

**Comment by bilibili-ayang** [comment]
当前问题是 tauri 这边的绑定快捷键的 bug，如果想让 linux 调用快捷键成功，就不能支持 linux 修改快捷键！

**Comment by bilibili-ayang** [comment]
感谢反馈，当前问题是 tauri 这边的绑定快捷键的 bug，我们这边会看看 tauri 有没有给出解决方法，如果没有，我们自己会出一个解决方案，以供 linux 用户正常使用！
