### ISSUE TITLE
Windows版本运行正常但会弹出警示框

### ISSUE THREAD

**Issue by KLiuZC** [ChatGPT-Desktop/ChatGPT-Desktop#109]
Windows可以正常运行进行问答，但问出第一个问题后会弹出一个警示框

请求出错: Network Error: lo Error: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。(os error 10060): loError: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。(os error 10060)

![256db843382736776afca60677de535.png](https://s2.loli.net/2023/03/27/OfNBn2ysuKAorWx.png)

**Comment by bilibili-ayang** [comment]
感谢反馈，可能是你网络问题导致的，建议你参考文档常见问题 1
