### ISSUE TITLE
找不到 Windows 版保存回答成为 md 文件的路径

### ISSUE THREAD

**Issue by KLiuZC** [ChatGPT-Desktop/ChatGPT-Desktop#113]
点击保存回答生成 md 文件后，找不到这个文件在哪里。希望能自定义 md 文件的保存路径

**Comment by bilibili-ayang** [comment]
感谢反馈，我们这边测试修复一下！

**Comment by bilibili-ayang** [comment]
我们这边测试了没问题，windows 保存也是在下载文件夹下，下个版本会导出成功后直接打开 download 文件夹！
