### ISSUE TITLE
chatGpt回答完成会报”更新数据时遇到了问题，请重试“

### ISSUE THREAD

**Issue by Amourtani** [ChatGPT-Desktop/ChatGPT-Desktop#122]
![1679998600307](https://user-images.githubusercontent.com/48053221/228205720-689e360f-2b39-4d58-afbf-e466e4ef814b.png)

但是可以继续使用

**Comment by Amourtani** [comment]
> 方方便的话，麻烦分享下回答，可能里面有特殊字符，导致错误，当然我们不好进行排查

今天没有遇到问题了，可能是网络问题

**Comment by bilibili-ayang** [comment]
> > 方方便的话，麻烦分享下回答，可能里面有特殊字符，导致错误，当然我们不好进行排查
> 
> 今天没有遇到问题了，可能是网络问题

好的，没问题我就关闭 issues 了！

**Comment by Amourtani** [comment]
> > > 方方便的话，麻烦分享下回答，可能里面有特殊字符，导致错误，当然我们不好进行排查
> > 
> > 
> > 今天没有遇到问题了，可能是网络问题
> 
> 好的，没问题我就关闭 issues 了！

可能确实是有特殊字符导致的，今天在同网络情况下，有时出现，有时不出现

**Comment by orangelckc** [comment]
收到，这个issue可以置顶下，持续收集一下因为特殊字符导致的报错吧

**Comment by bilibili-ayang** [comment]
@Amourtani 1.0.0 版本已对此问题进行修复，有问题再反馈哦！
