### ISSUE TITLE
啥时候支持4.0版本？

### ISSUE THREAD

**Issue by 775174143** [ChatGPT-Desktop/ChatGPT-Desktop#138]

**Comment by bilibili-ayang** [comment]
感谢反馈，我们暂时没有 4.0 账号测试，只能等我们有账号了才能支持！

**Comment by orangelckc** [comment]
在官方正式发布GPT4.0 API 之前应该不考虑接入4.0的功能，而且现在4.0的对话功能存在 25条/3小时的限制，使用并不方便。

**Comment by jl-1989** [comment]
> 在官方正式发布GPT4.0 API 之前应该不考虑接入4.0的功能，而且现在4.0的对话功能存在 25条/3小时的限制，使用并不方便。

现在取消这个限制了，建议考虑下

**Comment by orangelckc** [comment]
> > 在官方正式发布GPT4.0 API 之前应该不考虑接入4.0的功能，而且现在4.0的对话功能存在 25条/3小时的限制，使用并不方便。
> 
> 现在取消这个限制了，建议考虑下

新的版本已经支持4.0模型切换。
![image](https://github.com/Synaptrix/ChatGPT-Desktop/assets/48410934/5d021d57-76c1-4862-812c-b0a13f0de408)
