### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by lee946422** [ChatGPT-Desktop/ChatGPT-Desktop#144]
请问报错如下如何解决
![image](https://user-images.githubusercontent.com/68212870/229007338-d9ac67fa-7bd6-47a0-b3a5-ad4105b86264.png)

**Comment by bilibili-ayang** [comment]
感谢反馈，Windows 启动报错，是微软误报了，把软件列入白名单试试呢！

**Comment by bilibili-ayang** [comment]
置顶 issues 只加入解决方案，这个 issues 我就关啦！
