### ISSUE TITLE
开发环境启动报错

### ISSUE THREAD

**Issue by Quanzhitong** [ChatGPT-Desktop/ChatGPT-Desktop#145]
chunk-RCPA6UVN.js:1 Uncaught TypeError: window.__TAURI_IPC__ is not a function

**Comment by bilibili-ayang** [comment]
感谢反馈，你是在网页端打开吗？网页端打不开哦，此项目是 app，所以需要用 pnpm tauri dev 启动，直到 app 出现！

**Comment by bilibili-ayang** [comment]
> 感谢反馈，你是在网页端打开吗？网页端打不开哦，此项目是 app，所以需要用 pnpm tauri dev 启动，直到 app 出现！

npm 和 yarn 等也可以！
