### ISSUE TITLE
软件启动拨错

### ISSUE THREAD

**Issue by lee946422** [ChatGPT-Desktop/ChatGPT-Desktop#146]
![image](https://user-images.githubusercontent.com/68212870/229013330-22a723c2-3fc7-4b0f-9549-bef820908272.png)

尝试关闭防火墙修复无效
![image](https://user-images.githubusercontent.com/68212870/229013564-d5499fd5-94cf-47d0-b04f-d13627f6adc0.png)

**Comment by bilibili-ayang** [comment]
启动报错，将软件加入白名单试试呢

**Comment by bilibili-ayang** [comment]
@lee946422 置顶 issues 给出了 windows 解决方案的步骤，可以参考一下！这个 issues 我就关啦！

**Comment by lee946422** [comment]
没有发现所描述的置顶解决方案，请给一下具体链接，谢谢




warmbaby
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ChatGPT-Desktop/ChatGPT-Desktop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月31日(星期五) 下午2:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ChatGPT-Desktop/ChatGPT-Desktop] 软件启动拨错 (Issue #146)





 
@lee946422 置顶 issues 给出了 windows 解决方案的步骤，可以参考一下！这个 issues 我就关啦！
