### ISSUE TITLE
复制功能能否支持直接复制markdown源文件

### ISSUE THREAD

**Issue by rayepeng** [ChatGPT-Desktop/ChatGPT-Desktop#151]
<img width="758" alt="image" src="https://user-images.githubusercontent.com/36496433/229037016-05724e7a-96dc-4a84-855b-fba2d4013a0b.png">

复制结果为：
以下是一个简单的 Python 代码，实现了一个基本的加法运算：
a = 5
b = 3
c = a + b
print(c)
输出结果为：
8
其中，变量 a 和 b 分别赋值为 5 和 3，然后将它们相加并赋值给变量 c，最后通过 print() 函数将结果输出。

希望支持直接复制markdown

**Comment by bilibili-ayang** [comment]
感谢反馈，下个版本加入复制纯文字和 markdown 的两种方式！

**Comment by bilibili-ayang** [comment]
@rayepeng 复制 markdown 功能已支持，期待下个版本更新！
