### ISSUE TITLE
MacOS 11.7.4 打开一片空白

### ISSUE THREAD

**Issue by cnscottluo** [ChatGPT-Desktop/ChatGPT-Desktop#33]

**Comment by bilibili-ayang** [comment]
大概知道这个问题，因为我们项目用了最新的 esnext 特性，对 webkit 内核版本要求比较高，你这边方便的话提供一下 webkit 内核版本！

在Mac电脑上查看WebKit内核版本的方法如下：

1. 打开Safari浏览器。

2. 点击菜单栏中的“Safari”选项。

3. 在下拉菜单中选择“关于Safari”。

4. 弹出的窗口中会显示Safari浏览器的版本号和WebKit内核版本号。

我这边可以向下兼容一下，使得内核版本低也可以正常使用！

**Comment by cnscottluo** [comment]
<img width="284" alt="image" src="https://user-images.githubusercontent.com/10561969/226335517-fc1e2b73-0a16-4ab4-8177-42d9a2a209b3.png">

**Comment by bilibili-ayang** [comment]
好的，我们这边后续会进行向下兼容，倒是你这边在试试！

**Comment by bilibili-ayang** [comment]
如果方便的话进我们的 dc 社区，这边提供一个新的 beta 版本，你测试一下！
