### ISSUE TITLE
程序窗口快捷键切换效果的建议

### ISSUE THREAD

**Issue by Daydreamcgy** [ChatGPT-Desktop/ChatGPT-Desktop#58]
1. 为快捷键切换加上淡入效果，不会太突兀。
2. 按以下步骤有个不好的体验： 
    ①快捷键呼出窗口  ②用鼠标到windows任务栏点击图标隐藏窗口 ③用快捷键呼出窗口；
   此时是不能正常呼出窗口的，必须用鼠标点击任务栏的图标来打开。

以上两点我均参考everything。

**Comment by bilibili-ayang** [comment]
感谢反馈，我们这边解决一下，也欢迎 pr 哦！

**Comment by orangelckc** [comment]
呼出的问题已在 #62 中解决

**Comment by bilibili-ayang** [comment]
切换动画你是指窗口被呼出的淡入动画吗？你是什么操作系统？

**Comment by Daydreamcgy** [comment]
> 切换动画你是指窗口被呼出的淡入动画吗？你是什么操作系统？

我是window10

**Comment by l1m2e** [comment]
> > 切换动画你是指窗口被呼出的淡入动画吗？你是什么操作系统？
> 
> 我是窗口10

你可以检查一下是否开启了 windows10 的动画

**Comment by l1m2e** [comment]
> > 切换动画你是指窗口被呼出的淡入动画吗？你是什么操作系统？
> 
> 我是窗口10

你可以检查一下是否开启了windows10的动画   你可以通过快捷键 win+i 打开设置 找到轻松启动 如下图
![image](https://user-images.githubusercontent.com/62976143/227401600-3e8b3059-349b-4ee6-80ea-b9855d40643c.png)

win+s 搜索 查看高级系统设置  性能-> 设置 查看是否设置最佳外观

![image](https://user-images.githubusercontent.com/62976143/227401927-abbe539c-b5ac-4194-a321-a99269df60a8.png)

如果上述都不符合您的需求  你可以提供一个 gif 或者视频来给我们演示一你您需要的效果

**Comment by Daydreamcgy** [comment]
<img width="840" alt="4f574384830f50bd4c70d39a0bec3fe" src="https://user-images.githubusercontent.com/61179540/227407052-f3b88523-265c-46d0-b1d4-97378dcb7cab.png">

https://user-images.githubusercontent.com/61179540/227406965-089409fb-464a-4a65-84b6-8fefeb7544cc.mp4

其实也没那么重要，也可能是我自身的原因。

**Comment by Daydreamcgy** [comment]
<img width="395" alt="6db5304b11b641d1cc4ab5f1c0ec955" src="https://user-images.githubusercontent.com/61179540/227407266-e5aa7162-a494-4494-983d-11aa3a15f9ca.png">

**Comment by l1m2e** [comment]
在我的 windows(windows10 ltsc) 上它是有动画效果的，但是动画时间并没有 everything 的动画时间长，我们当前目标是完善页面功能，这个动画的功能我们暂时不考虑，如果以后有时间我们可以看看 tauri 有没有解决办法，当然，也欢迎你查看相关生态或者解决办法来提交 pr！
