### ISSUE TITLE
接口会报错

### ISSUE THREAD

**Issue by fwcxy** [ChatGPT-Desktop/ChatGPT-Desktop#92]
![image](https://user-images.githubusercontent.com/68321741/227461411-3355df85-b78e-46e2-a20a-75f2eed8b345.png)

**Comment by bilibili-ayang** [comment]
感谢反馈，此问题已修复，会在下个版本更新后提示相对应的报错原因，目前咱们就只对获取账户余额的 api 做了报错提示，所以这个报错就是你的 key 填写不正确，或者网络问题！

**Comment by fwcxy** [comment]
那应该是梯子问题了 我这个梯子用网站也是提问一次要刷新一下页面

**Comment by bilibili-ayang** [comment]
ok，找到问题所在就行，我这边关闭 issues 啦！
